# Generated by Django 4.2.7 on 2023-11-07 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='bafnotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice', models.CharField(max_length=400)),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='bmsnotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice', models.CharField(max_length=400)),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='bsccsnotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice', models.CharField(max_length=400)),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='bscitnotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice', models.CharField(max_length=400)),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('number', models.CharField(max_length=10)),
                ('message', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('course', models.CharField(max_length=50)),
                ('profile_img', models.ImageField(blank=True, default='media/default.jpg', null=True, upload_to='media')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('gender', models.CharField(max_length=10)),
                ('alternative_phone', models.CharField(max_length=10)),
                ('parent_phone', models.CharField(max_length=10)),
                ('address', models.TextField(max_length=500)),
                ('district', models.CharField(max_length=20)),
                ('tehsil', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of birth (yyyy-mm-dd):')),
                ('mother_tongue', models.CharField(max_length=15)),
                ('martial_status', models.CharField(max_length=10)),
                ('nationality', models.CharField(max_length=15)),
                ('state_of_domicile', models.CharField(max_length=25)),
                ('adhaar_number', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', models.FileField(upload_to='media')),
                ('uniform', models.FileField(upload_to='media')),
                ('hsc_result', models.FileField(upload_to='media')),
                ('reservation_certificate', models.FileField(blank=True, null=True, upload_to='media', verbose_name='Reservation Certificate')),
                ('pc_certificate', models.FileField(blank=True, null=True, upload_to='media', verbose_name='Physically Challeged Certificate')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=10)),
                ('science', models.BooleanField(null=True)),
                ('commerce', models.BooleanField(null=True)),
                ('art', models.BooleanField(null=True)),
                ('minority', models.BooleanField(null=True)),
                ('physically', models.BooleanField(null=True, verbose_name='Physically chanlleged')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AcademicDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssc_school_name', models.CharField(max_length=30)),
                ('ssc_school_board', models.CharField(max_length=10)),
                ('ssc_passing_year', models.DateField(max_length=10)),
                ('ssc_rollno', models.CharField(max_length=6)),
                ('ssc_marks', models.CharField(max_length=3)),
                ('ssc_class_grade', models.CharField(blank=True, max_length=10, null=True)),
                ('ssc_class_percent', models.IntegerField(blank=True, null=True)),
                ('hsc_school_name', models.CharField(max_length=30)),
                ('hsc_school_board', models.CharField(max_length=10)),
                ('hsc_passing_year', models.DateField(max_length=10)),
                ('hsc_rollno', models.CharField(max_length=6)),
                ('hsc_marks', models.CharField(max_length=3)),
                ('hsc_class_grade', models.CharField(blank=True, max_length=10, null=True)),
                ('hsc_class_percent', models.IntegerField(blank=True, null=True)),
                ('hsc_maths_mark', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
