# Generated by Django 4.2.7 on 2023-11-07 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicdetails',
            name='hsc_passing_year',
            field=models.DateField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='academicdetails',
            name='ssc_passing_year',
            field=models.DateField(max_length=10, null=True),
        ),
    ]
