# Generated by Django 4.2.7 on 2023-11-08 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0002_alter_academicdetails_hsc_passing_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicdetails',
            name='hsc_class_grade',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='academicdetails',
            name='hsc_school_board',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='academicdetails',
            name='ssc_class_grade',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='academicdetails',
            name='ssc_school_board',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='categorydetails',
            name='category',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='gender',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='martial_status',
            field=models.CharField(max_length=30),
        ),
    ]
