# Generated by Django 4.2.7 on 2023-12-20 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0003_alter_academicdetails_hsc_class_grade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UIchanger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=10)),
                ('admission_desk_number', models.CharField(max_length=12)),
                ('college_tel_number_1', models.CharField(max_length=10)),
                ('college_tel_number_2', models.CharField(max_length=10)),
                ('college_email', models.EmailField(max_length=254)),
                ('college_map_link', models.URLField(blank=True, null=True)),
                ('college_img_1', models.ImageField(blank=True, default='media/default.jpg', null=True, upload_to='media')),
                ('college_img_2', models.ImageField(blank=True, default='media/default.jpg', null=True, upload_to='media')),
                ('college_img_3', models.ImageField(blank=True, default='media/default.jpg', null=True, upload_to='media')),
                ('college_img_4', models.ImageField(blank=True, default='media/default.jpg', null=True, upload_to='media')),
                ('college_logo', models.ImageField(blank=True, default='media/default.jpg', null=True, upload_to='media')),
                ('for_career_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
