# Generated by Django 4.2.7 on 2023-12-20 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0004_uichanger'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UIchanger',
            new_name='change_1',
        ),
    ]
